"""Trial generator and runner.

A "trial" is one closed-loop episode with one disturbance. It is described by a
small dict (the spec), so that what was run is fully recorded and every trial
can be reproduced from its row in the CSV:

    block       which experiment it belongs to (calib / main / boundary_*)
    true_class  "body", "world" or "none" (undisturbed, calibration only)
    param       body parameter changed ("l" or "m"), body trials only
    factor      multiplier applied to that parameter, body trials only
    torque      external torque in N*m (signed), world trials only
    duration    push length in steps, world trials only
    onset       step at which the disturbance starts
    seed        start state + planner randomness

The two classes are generated by separate functions and never mixed: a body
trial has no push, a world trial has no parameter change.
"""
import multiprocessing as mp
import os

import numpy as np
import torch

import classifier
import classify_config as cc
import model as model_lib
import run_experiment

HERE = os.path.dirname(os.path.abspath(__file__))


# ---------------------------------------------------------------------------
# Generating specs
# ---------------------------------------------------------------------------

def _onset(rng):
    return int(rng.integers(cc.ONSET_MIN, cc.ONSET_MAX + 1))


def body_spec(rng, block, seed, param=None, factor=None):
    """A body-change trial. Random parameter and factor unless given."""
    return dict(block=block, true_class=classifier.BODY,
                param=param or str(rng.choice(cc.BODY_PARAMS)),
                factor=float(factor if factor is not None
                             else rng.uniform(cc.BODY_FACTOR_MIN, cc.BODY_FACTOR_MAX)),
                torque=0.0, duration=0, onset=_onset(rng), seed=int(seed))


def world_spec(rng, block, seed, torque=None, duration=None):
    """A world-event trial. Random magnitude, sign and duration unless given.

    The sign is always random: a push to the left and a push to the right are
    the same kind of event, and fixing one direction could hide an asymmetry.
    """
    mag = torque if torque is not None else rng.uniform(cc.WORLD_TORQUE_MIN, cc.WORLD_TORQUE_MAX)
    sign = 1.0 if rng.random() < 0.5 else -1.0
    dur = duration if duration is not None else rng.integers(cc.WORLD_STEPS_MIN, cc.WORLD_STEPS_MAX + 1)
    return dict(block=block, true_class=classifier.WORLD, param="", factor=1.0,
                torque=float(sign * mag), duration=int(dur),
                onset=_onset(rng), seed=int(seed))


def none_spec(rng, block, seed):
    """An undisturbed trial. It still gets an onset, because the late-window
    score is measured relative to one; nothing happens there."""
    return dict(block=block, true_class="none", param="", factor=1.0,
                torque=0.0, duration=0, onset=_onset(rng), seed=int(seed))


def calibration_specs():
    rng = np.random.default_rng(cc.SEED_CALIB)
    return [none_spec(rng, "calib", cc.SEED_CALIB + i) for i in range(cc.N_CALIB)]


def main_specs():
    """N_PER_CLASS body trials and N_PER_CLASS world trials, randomised."""
    rng = np.random.default_rng(cc.SEED_MAIN)
    n = cc.N_PER_CLASS
    body = [body_spec(rng, "main", cc.SEED_MAIN + i) for i in range(n)]
    world = [world_spec(rng, "main", cc.SEED_MAIN + n + i) for i in range(n)]
    return body + world


def boundary_specs():
    """Fixed-magnitude grids for the boundary analysis (random onset/seed)."""
    rng = np.random.default_rng(cc.SEED_BOUNDARY)
    specs, seed = [], cc.SEED_BOUNDARY
    for param in cc.BODY_PARAMS:
        for f in cc.BOUNDARY_BODY_FACTORS:
            for _ in range(cc.N_BOUNDARY):
                specs.append(body_spec(rng, "boundary_body", seed, param, f)); seed += 1
    for tq in cc.BOUNDARY_TORQUES:
        for d in cc.BOUNDARY_DURATIONS:
            for _ in range(cc.N_BOUNDARY):
                specs.append(world_spec(rng, "boundary_world", seed, tq, d)); seed += 1
    return specs


# ---------------------------------------------------------------------------
# Running specs
# ---------------------------------------------------------------------------

def spec_to_condition(spec):
    """Translate a spec into the schedule format run_experiment understands."""
    if spec["true_class"] == classifier.BODY:
        return {"kind": "body", "factors": {spec["param"]: spec["factor"]}}
    if spec["true_class"] == classifier.WORLD:
        return {"kind": "world", "torque": spec["torque"], "duration": spec["duration"]}
    return {"kind": "none"}


_MODEL = None   # one frozen model per worker process


def _init_worker():
    global _MODEL
    torch.set_num_threads(1)   # parallelism comes from processes, not threads
    _MODEL = model_lib.load_model(os.path.join(HERE, run_experiment.config.MODEL_PATH))


def run_trial(spec):
    """Run one episode and return the spec plus its measured outcome.

    The episode is only as long as it needs to be: onset + late window + a
    small margin. Classification is NOT done here, because the threshold
    may not be known yet (it is calibrated from other trials).
    """
    steps = spec["onset"] + cc.LATE_END + cc.EPISODE_MARGIN
    rows = run_experiment.run_episode(_MODEL, spec_to_condition(spec),
                                      seed=spec["seed"], steps=steps, onset=spec["onset"])
    errors = np.array([r["surprise"] for r in rows])
    theta_end = abs(rows[spec["onset"] + cc.LATE_END - 1]["theta"])
    out = dict(spec)
    out["score"] = classifier.late_window_score(errors, spec["onset"])
    out["pre_onset_mean"] = float(errors[:spec["onset"]].mean())
    out["peak_after_onset"] = float(errors[spec["onset"]:spec["onset"] + cc.LATE_START].max())
    out["theta_end_of_window"] = float(theta_end)
    out["fell"] = bool(theta_end > cc.FELL_ANGLE)
    return out


def run_all(specs, label):
    """Run specs in parallel (N_WORKERS processes), printing progress."""
    print(f"  running {len(specs)} {label} trials on {cc.N_WORKERS} workers ...", flush=True)
    if cc.N_WORKERS <= 1:
        _init_worker()
        return [run_trial(s) for s in specs]
    ctx = mp.get_context("fork")
    with ctx.Pool(cc.N_WORKERS, initializer=_init_worker) as pool:
        out = []
        for i, r in enumerate(pool.imap(run_trial, specs, chunksize=2), 1):
            out.append(r)
            if i % 50 == 0 or i == len(specs):
                print(f"    {i}/{len(specs)}", flush=True)
    return out
